### ISSUE TITLE
How to estimate memory footprint from input parameter values?

### ISSUE THREAD

**Issue by chunhualiao** [Mantevo/miniFE#15]
Assuming we are only interested in OpenMP (miniFE/openmp45/src), not MPI.   

How to estimate the memory required for a given set of  input sizes (nx, ny and nz values)?

miniFE/openmp45/src]./miniFE.x -nx 512 -ny 512 -nz 512

```
MiniFE Mini-App, OpenMP Peer Implementation
Creating OpenMP Thread Pool...
Counted: 160 threads.
Running MiniFE Mini-App...
      creating/filling mesh...1.08418s, total time: 1.08418
generating matrix structure...Segmentation fault  **** 
```

Using 1024x1024x1024 generates "running out of memory"

```
./miniFE.x -nx 1024 -ny 1024 -nz 1024
MiniFE Mini-App, OpenMP Peer Implementation
Creating OpenMP Thread Pool...
Counted: 160 threads.
Running MiniFE Mini-App...
      creating/filling mesh...6.70102s, total time: 6.70103

generating matrix structure...proc 0 threw an exception in generate_matrix_structure, probably due to running out of memory. 
2.3012s, total time: 9.00222
         assembling FE data...
```

**Comment by nmhamster** [comment]
@chunhualiao - generally I used to run a 200 x 200 x 200 problem for our 16GB accelerators (think hardware like the Knight's Landing HBM memory). If you run a small problem (something like 100 x 100 x 100) in the YAML output file, look for a line that starts with `Global Memory (GB):`. This will give you the memory used for the main data structures (although there is some additional memory used to generate the problem etc). I would recommend running a few problems with increasing element count e.g. 125 x 125 x 125 etc, to see how the memory grows for your specific configuration and implementation. As above, roughly 200 x 200 x 200 gave good numbers for a 16GB HBM memory part. Does that help?

**Comment by chunhualiao** [comment]
Yes. It is helpful. Thank you!
